server:
  port: 8080
  error:
    path: /error

myhostname: 18.194.243.47
mail.debug: false
upload.path: /home/ec2-user/uploads
#recaptcha.secret: ${recaptcha-secret}
recaptcha.secret: 6LduQVoUAAAAACpkNtp9c5WWgyGENzIxZqF9SbZL

spring:
  application:
    name: sweater
  freemarker:
    expose-request-attributes: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    host: smtp.gmail.com
#    username: ${gmail-account-name}
#    password: ${gmail-account-pass}
    username: uw@dru.su
    password: 12345678
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

  # ===============================
  # = DB
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost/sweater
    username: postgres
    password: secret
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


# ===============================
# = Actuator
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: ALWAYS

logging:
  level:
    net.lelyak: debug


