#server:
#  port: 8082
#  error:
#    path: /error

myhostname: localhost:8080
mail.debug: true
upload.path: /home/nazar/Documents/sweater-uploads
recaptcha.secret: ${recaptcha-secret}

spring:
  application:
    name: sweater
  freemarker:
    expose-request-attributes: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    host: smtp.gmail.com
    username: ${gmail-account-name}
    password: ${gmail-account-pass}
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

  # ===============================
  # = DB
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost/sweater
    username: postgres
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


# ===============================
# = Actuator
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: ALWAYS

logging:
  level:
    net.lelyak: debug


