#server:
#  port: 8082
#  error:
#    path: /error

spring:
  application:
    name: sweater
  freemarker:
    expose-request-attributes: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    host: smtp.gmail.com
    username: uw@dru.su
    password: 12345678
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
mail.debug: true

  # ===============================
  # = DB
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost/sweater
    username: postgres
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# ===============================
# = Actuator
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: ALWAYS

logging:
  level:
    net.lelyak: debug

upload.path: /home/nazar/Documents/sweater-uploads

